### PR TITLE
Refactor/remove geneva

### PR DESCRIPTION
**Pull request by emielsteerneman**
Removed any and all occurences of the geneva drive. All targets are still compiling successfully.

### CODE REVIEW

**Comment by JaroKuiken** [comment]
LGTM, but with a quick scan I couldn't find a commit with the word geneva in it. Were there no geneva classes/variables to be removed?

**Comment by emielsteerneman** [comment]
I removed all variables / comments / classes / functions / tests etc that had anything to do with Geneva in all repos with a single commit per repo. (except for robothub, to keep the robots working)

**Comment by rolfvdhulst** [comment]
@emielsteerneman I'm confused. This PR contains no changes except from two spaces. Can we just close this?

**Review by rolfvdhulst — CHANGES_REQUESTED** [review]
There's no actual PR?

**Comment by emielsteerneman** [comment]
My bad. I thought the changes I made were all relevant so I just committed it all

**Pull request closed without merging**
