### PR TITLE
Fix bug in ShortestAngleDiff

### PR DESCRIPTION
**Pull request by HaicoDorenbos**
A bug in the ShortestAngleDiff function has been fixed. From now on always the shortest absolute angle is returned whereas in the past it could be the case that the longest angle was returned (that had a negative value).

### CODE REVIEW

**Comment by HaicoDorenbos** [comment]
Do not merge yet...

**Comment by HaicoDorenbos** [comment]
It could be merged from now on

**Review by RobotJente — CHANGES_REQUESTED** [review]
You are also removing functionality for finding the non-shortest difference between angles. Normally you could extrapolate this from the shortest diff, except that this now does not return the direction of the difference, which could be useful. Now we have a-b=b-a since it returns the abs

**Comment by HaicoDorenbos** [comment]
> You are also removing functionality for finding the non-shortest difference between angles. Normally you could extrapolate this from the shortest diff, except that this now does not return the direction of the difference, which could be useful. Now we have a-b=b-a since it returns the abs

This functionality was never used, except for the shortestAngleDiff function. And if you really want to use this functionality then you should use the - operator instead.

**Comment by HaicoDorenbos** [comment]
By the way this PR should simultaneously be merged with: Fix bug in ShortestAngleDiff #68 on the Roboteam_ai repository.

**Pull request merged**
