### PR TITLE
isOnLine() bug for cases where LineSegment is actually a Point

### PR DESCRIPTION
**Pull request by HaicoDorenbos**
The isOnLine() function behaves wrong for the case where the LineSegment is actually a point. I fixed this problem, but I expect more problems in the LineSegment for the cases where the LineSegment is actually a point. Since I am a parttimer I do not have the time to solve these problems, therefore I highly recommend someone else to look at this (I also created an issue for this). Also make sure you fix these problems in all code clones (because this functionality is cloned a lot also outside roboteam_utils, e.g. in ControlUtils on the roboteam_ai branch). Moreover take a look at Polygon, Triangle, Arcs and Circles for the cases where this things are actually points or lines and create test cases for these situations.

### CODE REVIEW

**Review by RobotJente — APPROVED** [review]
Looks good to me!

**Review by Yuhanun — APPROVED** [review]
lgtm

**Review by rolfvdhulst — CHANGES_REQUESTED** [review]
I am quite confused. When you work through the algebra the original method should already return true if all points are exactly equal (unless there are bugs in vector2's cross and dot product functions). Also, there's no test case for this (which I think you should have if you found a bug like this). 

In general for the line classes we need a different definition of points being 'equal' because any error can be scaled up by any amount by stepping along the line. In Vector2 we can get away with having equality being defined as ' close enough' but here that's not necessarily true. That's why I personally am not a fan of this change: you will create inconsistent behavior and potential errors. I would personally like to get away from having to use the margin that we use right now for calculation but unfortunately functions like sin() and cos() and the M_PI constants require us to have some margin for Vector2.

**Comment by rolfvdhulst** [comment]
Also in general, when you create a line which is a point you should maybe consider if it is not better to model it as a point. They are fundamentally different entities.

**Comment by HaicoDorenbos** [comment]
> I am quite confused. When you work through the algebra the original method should already return true if all points are exactly equal (unless there are bugs in vector2's cross and dot product functions). Also, there's no test case for this (which I think you should have if you found a bug like this).
> 
> In general for the line classes we need a different definition of points being 'equal' because any error can be scaled up by any amount by stepping along the line. In Vector2 we can get away with having equality being defined as ' close enough' but here that's not necessarily true. That's why I personally am not a fan of this change: you will create inconsistent behavior and potential errors. I would personally like to get away from having to use the margin that we use right now for calculation but unfortunately functions like sin() and cos() and the M_PI constants require us to have some margin for Vector2.

The problem is when you have two points that are at two different locations then this function will return that they intersect which is not the case. I found this bug, because of the shadow test case with a single point. Also considering points equal if they are close enough is in my point of view a good modelling technique. For floats in general you should never check if they are equal but if they are close enough...

**Comment by HaicoDorenbos** [comment]
> Also in general, when you create a line which is a point you should maybe consider if it is not better to model it as a point. They are fundamentally different entities.

I do not agree with your point, a point is also a LineSegment. In case for the shadow function I also do not want to create a different function in case you have a point instead of a LineSegment. It is the task of the shadow function to deal with these cases, not the function that calls the shadow function.

**Pull request merged**
